import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import api, { describeApiError } from '../api';
import StatusPanel, { LoadingState } from '../components/StatusPanel';

const currency = (value) => `$${Number(value || 0).toFixed(2)}`;
const methods = [{ value: 'cash', label: 'Cash' }, { value: 'credit_card', label: 'Credit card' }, { value: 'check', label: 'Check' }];

export default function PaymentPage() {
  const { ticketId } = useParams(); const [ticket, setTicket] = useState(null); const [method, setMethod] = useState('');
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(null); const [outcome, setOutcome] = useState(null);
  useEffect(() => { document.body.classList.add('bg-payment'); return () => document.body.classList.remove('bg-payment'); }, []);
  const load = useCallback(async (signal) => { setLoading(true); setError(null); try { const loaded = (await api.get('/tickets/' + ticketId + '/', { signal })).data; setTicket(loaded); if (loaded.paid) setOutcome('already-paid'); } catch (requestError) { if (requestError?.code !== 'ERR_CANCELED') setError(describeApiError(requestError, 'Payment details could not be loaded.')); } finally { if (!signal?.aborted) setLoading(false); } }, [ticketId]);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load]);
  const pay = async (event) => { event.preventDefault(); if (!method || submitting) return; setSubmitting(true); setError(null); try { const response = await api.post('/tickets/' + ticketId + '/pay/', { payment_method: method }); setTicket(response.data.ticket || ticket); setOutcome('paid'); } catch (requestError) { if (requestError.response?.status === 409) setOutcome('already-paid'); else setError(describeApiError(requestError, 'Demo payment could not be confirmed.')); } finally { setSubmitting(false); } };
  if (loading) return <LoadingState label="Loading booking total…" />;
  if (!ticket) return <StatusPanel title={error?.title || 'Booking unavailable'} message={error?.message || 'Return to your dashboard and choose a booking.'} actionLabel="Retry" onAction={() => load()} />;
  const trip = ticket.train_trip || {}; const quote = ticket.quote || {};
  return <div className="page-stack payment-page"><ol className="journey-steps" aria-label="Booking progress"><li className="journey-steps__complete"><span>✓</span>Options</li><li className="journey-steps__current" aria-current="step"><span>2</span>Demo payment</li><li><span>3</span>Seat</li></ol>
    <div className="payment-layout"><section className="surface payment-summary" aria-labelledby="payment-summary-heading"><p className="eyebrow">{ticket.booking_reference}</p><h1 id="payment-summary-heading">{trip.origin_station} → {trip.destination_station}</h1><p>{trip.departure_time ? new Date(trip.departure_time).toLocaleString() : 'Departure time unavailable'}</p><dl className="fare-breakdown fare-breakdown--inverse"><div><dt>Base fare</dt><dd>{currency(quote.base_fare)}</dd></div>{quote.options?.map((item) => <div key={item.key}><dt>{item.name}</dt><dd>{currency(item.price)}</dd></div>)}<div><dt>Subtotal</dt><dd>{currency(quote.subtotal)}</dd></div><div><dt>Taxes & fees</dt><dd>{currency(quote.taxes_and_fees)}</dd></div><div className="fare-breakdown__total"><dt>Total</dt><dd>{currency(quote.total || ticket.amount)}</dd></div></dl><p className="demo-disclosure"><strong>Portfolio demo:</strong> no real money or financial details are collected.</p></section>
      <section className="surface payment-action" aria-labelledby="payment-action-heading">{outcome ? <><div className="success-state" role="status"><span className="completion-card__mark" aria-hidden="true">✓</span><p className="eyebrow">Booking confirmed</p><h2 id="payment-action-heading">Demo payment complete</h2><p>Your booking is ready. Choose a seat to finish your journey setup.</p></div><div className="completion-actions">{!ticket.seat_num && <Link className="button button--accent" to={'/select-seat/' + ticketId}>Choose a seat</Link>}<Link className="button button--secondary" to="/">Return to dashboard</Link></div></> : <form onSubmit={pay}><p className="eyebrow">Payment method</p><h2 id="payment-action-heading">How would you like to pay?</h2><fieldset className="payment-methods" disabled={submitting}><legend className="sr-only">Choose a demo payment method</legend>{methods.map((item) => <label key={item.value}><input type="radio" name="payment-method" value={item.value} checked={method === item.value} onChange={(event) => setMethod(event.target.value)} /><span><strong>{item.label}</strong><small>Used only as a demo booking label</small></span></label>)}</fieldset>{error && <StatusPanel title={error.title} message={error.message} variant="error" />}<button className="button button--accent button--large button--full" type="submit" disabled={!method || submitting}>{submitting ? 'Confirming…' : 'Confirm demo payment'}</button></form>}</section>
    </div></div>;
}
