import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api, { describeApiError } from './api';
import StatusPanel, { LoadingState } from './components/StatusPanel';

const formatDateTime = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Departure time unavailable';
function TicketCard({ ticket, busy, onCancel }) {
  const [managing, setManaging] = useState(false); const [confirming, setConfirming] = useState(false);
  const trip = ticket.train_trip || {}; const route = [trip.origin_station, trip.destination_station].filter(Boolean).join(' → ') || 'Journey details unavailable';
  const primary = !ticket.paid ? { to: '/payment/' + ticket.ticket_id, label: 'Complete demo payment' } : !ticket.seat_num ? { to: '/select-seat/' + ticket.ticket_id, label: 'Choose seat' } : { to: '/select-seat/' + ticket.ticket_id, label: 'View seat' };
  return <article className="ticket-card"><div className="ticket-card__topline"><div><p className="eyebrow">{ticket.booking_reference || `Ticket #${ticket.ticket_id}`}</p><h3>{route}</h3><p className="ticket-card__departure">{formatDateTime(trip.departure_time)} · Service {trip.service_number || '—'}</p></div><span className={'status-chip ' + (ticket.paid ? 'status-chip--success' : 'status-chip--pending')}>{ticket.paid ? 'Paid' : 'Payment needed'}</span></div>
    <dl className="ticket-facts"><div><dt>Seat</dt><dd>{ticket.seat_num ? `Seat ${ticket.seat_num}` : 'Not chosen'}</dd></div><div><dt>Total</dt><dd>${Number(ticket.amount || 0).toFixed(2)}</dd></div><div><dt>Train</dt><dd>{trip.consist_type || 'Not provided'}</dd></div></dl>
    <div className="ticket-actions"><Link className="button" to={primary.to}>{primary.label}</Link><button className="button button--quiet" onClick={() => setManaging((value) => !value)} aria-expanded={managing}>Manage booking</button></div>
    {managing && <div className="manage-panel"><p>Booked {ticket.booked_at ? new Date(ticket.booked_at).toLocaleDateString() : 'date unavailable'} · {ticket.payment_method ? ticket.payment_method.replace('_', ' ') : 'No payment method'}</p>{!confirming ? <button className="button button--danger-quiet" onClick={() => setConfirming(true)}>Cancel booking</button> : <div className="confirm-panel" role="alert"><div><strong>Cancel this booking?</strong><p>This releases its selected seat and cannot be undone here.</p></div><div className="confirm-panel__actions"><button className="button button--danger" onClick={() => onCancel(ticket.ticket_id)} disabled={busy}>{busy ? 'Cancelling…' : 'Yes, cancel booking'}</button><button className="button button--quiet" onClick={() => setConfirming(false)} disabled={busy}>Keep booking</button></div></div>}</div>}
  </article>;
}
function JourneyGroup({ title, description, tickets, busy, onCancel }) { if (!tickets.length) return null; return <section className="journey-group"><div className="section-intro section-intro--compact"><div><h2>{title}</h2><p>{description}</p></div><span className="count-badge">{tickets.length}</span></div><div className="ticket-list">{tickets.map((ticket) => <TicketCard key={ticket.ticket_id} ticket={ticket} busy={busy === ticket.ticket_id} onCancel={onCancel} />)}</div></section>; }

export default function Home() {
  const [user, setUser] = useState(null); const [tickets, setTickets] = useState([]); const [loading, setLoading] = useState(true);
  const [profileError, setProfileError] = useState(null); const [ticketsError, setTicketsError] = useState(null); const [actionError, setActionError] = useState(null); const [busy, setBusy] = useState(null);
  const [reward, setReward] = useState(null); const navigate = useNavigate();
  useEffect(() => { document.body.classList.add('bg-home'); const stored = sessionStorage.getItem('membershipReward'); if (stored) { try { setReward(JSON.parse(stored)); } catch {} sessionStorage.removeItem('membershipReward'); } return () => document.body.classList.remove('bg-home'); }, []);
  const load = useCallback(async (signal) => { setLoading(true); setProfileError(null); setTicketsError(null); const [profile, ownedTickets] = await Promise.allSettled([api.get('/me/', { signal }), api.get('/tickets/', { signal })]); if (profile.status === 'fulfilled') setUser(profile.value.data); else if (profile.reason?.code !== 'ERR_CANCELED') setProfileError(describeApiError(profile.reason, 'Membership details could not be loaded.')); if (ownedTickets.status === 'fulfilled') setTickets(ownedTickets.value.data); else if (ownedTickets.reason?.code !== 'ERR_CANCELED') setTicketsError(describeApiError(ownedTickets.reason, 'Bookings could not be loaded.')); setLoading(false); }, []);
  useEffect(() => { if (!localStorage.getItem('token')) { navigate('/login'); return undefined; } const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load, navigate]);
  const cancel = async (ticketId) => { setBusy(ticketId); setActionError(null); try { await api.delete('/tickets/' + ticketId + '/'); setTickets((current) => current.filter((item) => item.ticket_id !== ticketId)); const profile = await api.get('/me/'); setUser(profile.data); } catch (requestError) { setActionError(describeApiError(requestError, 'The booking could not be cancelled.')); } finally { setBusy(null); } };
  const grouped = useMemo(() => { const sorted = [...tickets].sort((a, b) => new Date(a.train_trip?.departure_time || 0) - new Date(b.train_trip?.departure_time || 0)); const needsAttention = sorted.filter((ticket) => !ticket.paid || !ticket.seat_num); const readyFuture = sorted.filter((ticket) => ticket.paid && ticket.seat_num && new Date(ticket.train_trip?.departure_time || 0) >= new Date()); return { needsAttention, next: readyFuture.slice(0, 1), other: sorted.filter((ticket) => !needsAttention.includes(ticket) && !readyFuture.slice(0, 1).includes(ticket)) }; }, [tickets]);
  const points = user?.membership_points ?? 0; const next = user?.membership_next_level; const progressBase = user?.membership_levels?.filter((level) => level.min_points_required <= points).at(-1)?.min_points_required || 0; const progress = next ? Math.min(100, ((points - progressBase) / (next.min_points_required - progressBase)) * 100) : 100;
  const pointsToNextLevel = next ? next.min_points_required - points : null;
  const membershipLevel = user?.membership_level || 'Bronze';
  const membershipTier = ['silver', 'gold', 'platinum'].includes(membershipLevel.toLowerCase()) ? membershipLevel.toLowerCase() : 'bronze';
  const name = user?.first_name || user?.username || user?.email?.split('@')[0] || 'traveler';
  return <div className="page-stack"><header className="dashboard-hero surface surface--hero compact-hero"><div><p className="eyebrow">Your journeys</p><h1>Welcome back, {name}</h1><p className="lede">Plan a trip, finish a booking, or check your next departure.</p></div><Link className="button button--accent" to="/flights">Find a train <span aria-hidden="true">→</span></Link></header>
    {reward && <section className="reward-reveal surface" role="status"><span aria-hidden="true">✦</span><div><p className="eyebrow">First-class reward</p><h2>+{reward.points} bonus point</h2><p>Seat {reward.seat} brings your membership total to {reward.total}.</p></div><button className="icon-button" aria-label="Dismiss reward" onClick={() => setReward(null)}>×</button></section>}
    {profileError ? <StatusPanel title={profileError.title} message="Your journeys may still be available below." actionLabel="Retry dashboard" onAction={() => load()} /> : loading && !user ? <LoadingState label="Loading membership…" /> : <section className={`membership-card membership-card--${membershipTier} surface`} data-membership-tier={membershipTier} aria-labelledby="membership-heading"><div className="membership-card__summary"><p className="eyebrow">Membership</p><h2 id="membership-heading" className="membership-title" aria-label={`${membershipLevel}, ${points} points`}><span className="membership-title__level">{membershipLevel}</span><span aria-hidden="true"> · </span><span>{points} points</span></h2><p>{next ? `${pointsToNextLevel} ${pointsToNextLevel === 1 ? 'point' : 'points'} to ${next.level_name}` : 'You have reached the top demo level.'}</p></div><div className="membership-progress" role="progressbar" aria-label="Progress to next membership level" aria-valuemin="0" aria-valuemax="100" aria-valuenow={Math.round(progress)}><span style={{ width: `${progress}%` }} /></div><p className="membership-rule">{user?.membership_earning_rule || 'Paid priority service and confirmed first-class seats earn points.'}</p></section>}
    <section aria-labelledby="bookings-heading"><div className="section-intro"><div><p className="eyebrow">Travel plans</p><h2 id="bookings-heading">Your bookings</h2></div><span className="count-badge">{tickets.length} total</span></div>{actionError && <StatusPanel title={actionError.title} message={actionError.message} variant="error" />}{loading && !tickets.length ? <LoadingState label="Loading your journeys…" /> : ticketsError ? <StatusPanel title={ticketsError.title} message={ticketsError.message} actionLabel="Retry bookings" onAction={() => load()} /> : !tickets.length ? <div className="empty-state surface"><h3>No bookings yet</h3><p>Search the demo timetable to plan your first journey.</p><Link className="button" to="/flights">Find trains</Link></div> : <><JourneyGroup title="Next journey" description="Your nearest confirmed departure." tickets={grouped.next} busy={busy} onCancel={cancel} /><JourneyGroup title="Needs attention" description="Complete payment or choose a seat." tickets={grouped.needsAttention} busy={busy} onCancel={cancel} /><JourneyGroup title="Other bookings" description="Later and past journeys." tickets={grouped.other} busy={busy} onCancel={cancel} /></>}</section>
  </div>;
}
