# Generated by Django 5.2.10 on 2026-01-12 04:06

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(blank=True, max_length=8, null=True)),
                ('min_points_required', models.IntegerField(blank=True, null=True)),
                ('perks_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'membership_level',
            },
        ),
        migrations.CreateModel(
            name='TrainTrip',
            fields=[
                ('trip_id', models.CharField(db_column='flight_id', max_length=10, primary_key=True, serialize=False)),
                ('service_number', models.IntegerField(blank=True, db_column='flight_number', null=True)),
                ('origin_station', models.CharField(blank=True, db_column='departure_airport', max_length=50, null=True)),
                ('destination_station', models.CharField(blank=True, db_column='arrival_airport', max_length=50, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('consist_type', models.CharField(blank=True, db_column='aircraft_type', max_length=50, null=True)),
                ('platform', models.CharField(blank=True, db_column='gate', max_length=25, null=True)),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(default='default_user', max_length=150, unique=True)),
                ('passport_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('email', models.CharField(max_length=75, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('membership_points', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('membership_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membershiplevel')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('membership_points', models.IntegerField(default=0)),
                ('membership_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.membershiplevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('seat_num', models.CharField(blank=True, max_length=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('check', 'Check'), ('cash', 'Cash')], max_length=12, null=True)),
                ('priority_boarding', models.BooleanField(default=False)),
                ('meal', models.BooleanField(default=False)),
                ('accommodation', models.BooleanField(default=False)),
                ('taxi', models.BooleanField(default=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger')),
                ('train_trip', models.ForeignKey(blank=True, db_column='flight_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.traintrip')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=25, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=7, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ticket')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=4)),
                ('seat_number', models.CharField(max_length=6)),
                ('travel_class', models.CharField(choices=[('standard', 'Standard'), ('first', 'First'), ('sleeper', 'Sleeper')], max_length=16)),
                ('train_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.traintrip')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('read_status', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('train_trip', models.ForeignKey(blank=True, db_column='flight_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.traintrip')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ticket')),
                ('train_trip', models.ForeignKey(blank=True, db_column='flight_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.traintrip')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
    ]
