# Generated by Django 5.2.9 on 2026-01-04 09:30

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=16)),
                ('min_points_required', models.IntegerField()),
                ('perks_description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'membership_level',
            },
        ),
        migrations.CreateModel(
            name='TrainTrip',
            fields=[
                ('train_trip_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('service_number', models.CharField(blank=True, max_length=10, null=True)),
                ('origin_station', models.CharField(max_length=50)),
                ('destination_station', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('consist_model', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='on_time', max_length=10)),
            ],
            options={
                'db_table': 'train_trip',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'core_user',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('membership_points', models.IntegerField(default=0)),
                ('membership_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.membershiplevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('seat_number', models.CharField(max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('cash', 'Cash'), ('check', 'Check')], max_length=12, null=True)),
                ('priority_boarding', models.BooleanField(default=False)),
                ('meal', models.BooleanField(default=False)),
                ('accommodation', models.BooleanField(default=False)),
                ('taxi', models.BooleanField(default=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger')),
                ('train_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.traintrip')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(max_length=3)),
                ('payment_method', models.CharField(max_length=25)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.ticket')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ticket')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('train_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.traintrip')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=4)),
                ('seat_number', models.CharField(max_length=6)),
                ('travel_class', models.CharField(choices=[('standard', 'Standard'), ('first', 'First'), ('sleeper', 'Sleeper')], max_length=16)),
                ('train_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.traintrip')),
            ],
            options={
                'db_table': 'seat',
                'unique_together': {('train_trip', 'car_number', 'seat_number')},
            },
        ),
    ]
